BankingApp.UI/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BankingApp.Models;
using BankingApp.UI.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BankingApp.UI.Controllers
{
    public class UserAccountController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        public UserAccountController(UserManager<ApplicationUser> userManager,SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.Email,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Accounts = new List<Account>()
                };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("index","home");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password,isPersistent:model.RememberMe,false);
                if (result.Succeeded)
                {
                    return RedirectToAction("index", "home");
                }
                
                ModelState.AddModelError(string.Empty, "Invalid Login Attempt!");
                
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("index", "home");
        }
    }
}

BankingApp.UI/Views/Shared/_BusinessList.cshtml
@model IEnumerable<BankingApp.Models.Account>
    
<hr/>
<h1>Business Accounts</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Account Number
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Balance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                Overdraft Rate
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.AccountType.Type == "Business")
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccountType.InterestRate)
            </td>
            <td>
                <a asp-action="Transactions" asp-route-id="@item.Id">Transactions</a> |
                @if (item.isClosed)
                {
                    <span>Closed</span>
                }
                else
                {
                    <a asp-action="Deposit" asp-route-id="@item.Id">Deposit</a> <span>|</span>
                    <a asp-action="Withdraw" asp-route-id="@item.Id">Withdraw</a> <span>|</span>
                    @if (item.Balance > 0)
                    {
                        <a asp-action="Transfer" asp-route-id="@item.Id">Transfer</a> <span>|</span>
                    }
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> <span>|</span>
                    <a asp-action="Delete" asp-route-id="@item.Id"> Close Account </a>
                }
            </td>
        </tr>
            }
        }
    </tbody>
</table>

BankingApp.UI/Views/Shared/_CheckingList.cshtml
@model IEnumerable<BankingApp.Models.Account>

<h1>Checking Accounts</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Account Number
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Balance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                Interest Rate
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.AccountType.Type == "Checking")
            { 
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>

            <td>
                $@Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccountType.InterestRate)
            </td>
            <td>
                <a asp-action="Transactions" asp-route-id="@item.Id">Transactions</a> |
                @if (item.isClosed)
                {
                    <span>Closed</span>
                }
                else
                {
                    <a asp-action="Deposit" asp-route-id="@item.Id">Deposit</a> <span>|</span>
                    <a asp-action="Withdraw" asp-route-id="@item.Id">Withdraw</a> <span>|</span>
                    <a asp-action="Transfer" asp-route-id="@item.Id">Transfer</a> <span>|</span>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> <span>|</span>
                    <a asp-action="Delete" asp-route-id="@item.Id"> Close Account </a>
                }

            </td>
        </tr>
            } 
        }
    </tbody>
</table>

BankingApp.UI/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;
@inject UserManager<ApplicationUser> userManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Big Bank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="background-color:lightblue">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Big Bank</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form asp-controller="UserAccount" asp-action="logout">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAccount" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAccount" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav flex-grow-1" role="menu">
                        @if (signInManager.IsSignedIn(User))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">My Accounts</a>
                            </li>
                            <li class="dropdown text-dark" style="margin:.5em">
                                <a href="#" class="dropdown-toggle text-dark" data-toggle="dropdown" role="button" style="border-color : Lime">Open new Account </a>

                                <ul class="dropdown-menu">
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="CreateChecking">Checking Account</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="CreateBusiness">Business Account</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="CreateLoan">Loan</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="CreateTD">Term Deposit</a></li>
                                </ul>
                            </li>
                            


                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }

                    </ul>


                </div>
            </div>
        </nav>

    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @*<video autoplay muted loop id="myVideo">
                    <source src="C:\Users\Henri\Revature\Workarea\Project1\BankingApp.UI\wwwroot\video.mp4" type="video/mp4">
                </video>*@
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:lightblue">
        <div class="container">
            &copy; 2019 - Big Bank - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BankingApp.UI/Views/Shared/_LoanList.cshtml
@model IEnumerable<BankingApp.Models.Account>

<hr />
<h1>Loans</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                Account Number
            </th>

            <th>
                Principle
            </th>
            <th>
                Date Created
            </th>
            <th>
                Interest Rate
            </th>
            <th>
                Term (Months)
            </th>
            <th>
                Total Due
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.AccountType.Type == "Loan")
            { 
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccountType.InterestRate)
            </td>


            <td>
                @item.Loans.Where(m => m.AccountId == item.Id).SingleOrDefault().Term
            </td>

            <td>
                $@Html.DisplayFor(modelItem => item.Loans.FirstOrDefault(l => l.AccountId == item.Id).TotalDue)
            </td>
            <td>
                <a asp-action="Transactions" asp-route-id="@item.Id">Transactions</a> |
                @if (item.isClosed)
                {
                    <span>Closed</span>
                }
                else
                {
                    <a asp-action="PayLoan" asp-route-id="@item.Id">Pay Loan</a>
                }

            </td>
        </tr>
            }
            
        }
    </tbody>
</table>

BankingApp.UI/Views/Shared/_TDList.cshtml
@model IEnumerable<BankingApp.Models.Account>

<hr />
<h1>Term Deposits</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                Account Number
            </th>
            <th>
                Principle
            </th>
            <th>
                Date Created
            </th>
            <th>
                Interest Rate
            </th>
            <th>
                Term (Months)
            </th>
            <th>
                Total Earnings
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.AccountType.Type == "Term Deposit")
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccountType.InterestRate)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.TermDeposits.FirstOrDefault(l => l.AccountId == item.Id).Term)
            </td>

            <td>
                $@Html.DisplayFor(modelItem => item.TermDeposits.FirstOrDefault(l => l.AccountId == item.Id).TotalDue)
            </td>


            <td>
                <a asp-action="Transactions" asp-route-id="@item.Id">Transactions</a> |
                @if (item.isClosed)
                {
                    <span>Closed</span>
                }
                else
                {
                    <a asp-action="Withdraw" asp-route-id="@item.Id">Withdraw</a>

                }
            </td>
        </tr>
            }

        }
    </tbody>
</table>

BankingApp.UI/Views/Shared/_TransactionList.cshtml
@model IEnumerable<BankingApp.Models.Transaction>

<table class="table">
    <thead>
        <tr>
            <th>
                Amount
            </th>
            <th>
                Type
            </th>
            <th>
                Date Stamp
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    $@Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TransactionType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateStamp)
                </td>

            </tr>
        }
    </tbody>
</table>